triggers:
- description: null
  envs: []
  last_enabled_at: 2024-08-01 19:28:02.548536
  name: cnpj_data_pipeline_script
  pipeline_uuid: cnpj_data_pipeline_script
  schedule_interval: @daily
  schedule_type: time
  settings:
   landing_time_enabled: true
  sla: null
  start_time: 2024-08-01 08:00:00
  status: active
  variables: []