default:
  aws_access_key_id: YOUR_AWS_ACCESS_KEY_ID
  aws_secret_access_key: YOUR_AWS_SECRET_ACCESS_KEY
  aws_session_token: YOUR_AWS_SESSION_TOKEN  # Optional if using temporary credentials.
  region_name: YOUR_AWS_REGION               # e.g., us-east-1.
  bucket_name: your-data-lake                # The S3 bucket where data will be stored.
  data_prefix: receita-federal/estabelecimentos/ # Prefix for organizing S3 objects.
  output_format: csv                         # Format in which processed data will be stored.
  logging_level: INFO                        # Level of logging output.
  retries: 3                                 # Number of retries for failed S3 operations.
